export const karmaLevelData = [
  {
    name: "Abyssal Fin",
    desc: "The Abyssal Fin represents represents the origins. It signifies the very beginning. Its scales shimmer with resilience. This level symbolizes Initiation, Curiosity, and the Foundation of your journey.",
    img: "https://res.cloudinary.com/dddnxiqpq/image/upload/v1711619528/f8913a51dbe27907e46814314f29a427_slgvk2.png",
    requiredKarma: 250,
    startsFrom: 0,
    tokenId: 0,
  },
  {
    name: "Amphiblaze",
    desc: "Amphiblaze, the second stage, embodies adaptation. It combines aquatic and terrestrial elements. This level signifies versatility and the art of thriving in diverse environments.",
    img: "https://res.cloudinary.com/dddnxiqpq/image/upload/v1711619103/1442f2e197f7b1f65a6e9a6c66eac8ed48844215_sdfkym.png",
    requiredKarma: 500,
    startsFrom: 250,
    tokenId: 1,
  },
  {
    name: "Reptilith",
    desc: "The Reptilith portrays resilience of the reptilian lineage that survived through epochs.This level represents resilience, shedding old patterns, and the ability to thrive in harsh conditions.",
    img: "https://res.cloudinary.com/dddnxiqpq/image/upload/v1711619528/f8913a51dbe27907e46814314f29a427_slgvk2.png",
    requiredKarma: 1000,
    startsFrom: 500,
    tokenId: 2,
  },
  {
    name: "Avian Ember",
    desc: "Avian Ember symbolize freedom. As a bird soaring above the canopy. Our choices ripple through the air, affecting distant lands.  This level represents exploration, and the power to transcend boundaries. ",
    img: "https://res.cloudinary.com/dddnxiqpq/image/upload/v1711619528/f8913a51dbe27907e46814314f29a427_slgvk2.png",
    requiredKarma: 2000,
    startsFrom: 1000,
    tokenId: 3,
  },
  {
    name: "Metamorphix",
    desc: "Metamorphix captures transformation. A cocoon hangs from a branch, promising rebirth. Just as caterpillars become butterflies, It evolve. The impact shifts from consumption to conservation with newfound purpose.",
    img: "https://res.cloudinary.com/dddnxiqpq/image/upload/v1711619528/f8913a51dbe27907e46814314f29a427_slgvk2.png",
    requiredKarma: 3000,
    startsFrom: 2000,
    tokenId: 4,
  },
  {
    name: "Primate Sage",
    desc: "Primate Sage portrays an ape perched on a bough. Our ancestors, like apes, shaped ecosystems with knowledge and empathy.This level embodies wisdom, community, and the responsibility to bridge past and future.",
    img: "",
    requiredKarma: 4000,
    startsFrom: 3000,
    tokenId: 5,
  },
  {
    name: "Homo Terraformus",
    desc: "Homo Terraformus stands tall. A human figure sculpting landscapes.This level signifies stewardship—our duty to conserve, restore, and harmonize with nature.",
    img: "https://res.cloudinary.com/dddnxiqpq/image/upload/v1711619528/f8913a51dbe27907e46814314f29a427_slgvk2.png",
    requiredKarma: 5000,
    startsFrom: 4000,
    tokenId: 6,
  },
  {
    name: "Technobotanist",
    desc: "Technobotanist melds nature and technology. Robotic tendrils weave through leaves, analyzing chlorophyll. This level embodies balance between progress and preservation.",
    img: "https://res.cloudinary.com/dddnxiqpq/image/upload/v1711619528/f8913a51dbe27907e46814314f29a427_slgvk2.png",
    requiredKarma: 7500,
    startsFrom: 5000,
    tokenId: 7,
  },
  {
    name: "Cognitron",
    desc: "Cognitron, with the power of AI neural network, pulses with data. It learns from ecosystems, predicting patterns.This level represents insight, computation, and the quest for a harmonious world. ",
    img: "https://res.cloudinary.com/dddnxiqpq/image/upload/v1711619528/f8913a51dbe27907e46814314f29a427_slgvk2.png",
    requiredKarma: 10000,
    startsFrom: 7500,
    tokenId: 8,
  },
  {
    name: "Gaiaforge",
    desc: "Gaiaforge transcends—part deity, part steward. It cradles Earth, forging destiny.This pinnacle level embodies mastery, cosmic responsibility, and weaving fate for generations to come.",
    img: "https://res.cloudinary.com/dddnxiqpq/image/upload/v1711619528/f8913a51dbe27907e46814314f29a427_slgvk2.png",
    requiredKarma: 20000,
    startsFrom: 10000,
    tokenId: 9,
  },
];
